name: build-debug

on:
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - "buildozer.spec"
      - ".github/workflows/android-debug.yml"
      - "requirements.txt"
      - "pyproject.toml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-debug:
    runs-on: ubuntu-24.04

    env:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_PYTHON_VERSION_WARNING: "1"
      BUILDOZER_WARN_ON_ROOT: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip \
            python3-venv python3-pip \
            libffi-dev libssl-dev libbz2-dev libsqlite3-dev zlib1g-dev \
            libncurses5-dev libncursesw5-dev libreadline-dev libgdbm-dev liblzma-dev \
            autoconf automake libtool pkg-config cmake curl

      - name: Restore caches
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            ~/.buildozer
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: Linux-buildozer-${{ hashFiles('buildozer.spec') }}-${{ hashFiles('requirements.txt', 'pyproject.toml') }}
          restore-keys: |
            Linux-buildozer-

      - name: Create venv & install tools
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install "cython>=3.0" buildozer

      # Installiert SDK in /usr/local/lib/android/sdk (beschreibbar) und setzt ANDROID_* Variablen
      - name: Install Android SDK skeleton
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools

      # Robust: sdkmanager finden/ggf. cmdline-tools nachinstallieren, Lizenzen akzeptieren, API/Build-Tools 34 pinnen.
      - name: Prepare Android SDK (licenses + API/BT pins)
        shell: bash
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          set -euo pipefail

          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}"
          echo "ANDROID_HOME=${ANDROID_HOME}"
          mkdir -p "${ANDROID_SDK_ROOT}"

          # 1) sdkmanager ermitteln oder cmdline-tools 'latest' nachinstallieren
          SDKMANAGER="$(command -v sdkmanager || true)"
          if [ -z "${SDKMANAGER}" ]; then
            if [ -x "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" ]; then
              SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
            else
              echo "Installing cmdline-tools (latest)…"
              mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
              curl -L -o /tmp/cmdtools.zip "https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip"
              unzip -q /tmp/cmdtools.zip -d "${ANDROID_SDK_ROOT}/cmdline-tools"
              # entpackt als 'cmdline-tools'; nach 'latest' verschieben (von Google so empfohlen)
              mv "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools" "${ANDROID_SDK_ROOT}/cmdline-tools/latest"
              SDKMANAGER="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager"
              chmod +x "${SDKMANAGER}"
            fi
          fi
          echo "Using sdkmanager at: ${SDKMANAGER}"

          yes | "${SDKMANAGER}" --licenses

          "${SDKMANAGER}" --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"

          # 2) Falls 36.x Build-Tools irgendwie reingekommen sind → entfernen
          rm -rf "${ANDROID_SDK_ROOT}/build-tools/36."* || true
          rm -rf "${HOME}/.buildozer/android/platform/android-sdk/build-tools/36."* || true

          echo "Installed build-tools:"
          ls -1 "${ANDROID_SDK_ROOT}/build-tools" || true
          echo "Installed platforms:"
          ls -1 "${ANDROID_SDK_ROOT}/platforms" || true

      - name: Build debug APK
        shell: bash
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          source .venv/bin/activate
          set -o pipefail
          # Buildozer findet das SDK über ANDROID_SDK_ROOT/ANDROID_HOME
          buildozer -v android debug 2>&1 | tee buildozer.log

      - name: Diagnostics (list outputs)
        if: always()
        run: |
          echo "== tree bin (if exists) =="
          (ls -la bin && find bin -maxdepth 2 -type f) || echo "no bin dir"
          echo "== search for APK/AAB under .buildozer =="
          find .buildozer -type f \( -name "*.apk" -o -name "*.aab" \) -printf "%p\n" || true

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            buildozer.log
            .buildozer/android/platform/*.txt
            .buildozer/android/platform/*/gradle-*.log
          if-no-files-found: warn

      - name: Upload APK/AAB (best-effort)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spectro-android-outputs
          path: |
            bin/**/*.apk
            bin/**/*.aab
            .buildozer/**/outputs/**/*.apk
            .buildozer/**/outputs/**/*.aab
            .buildozer/android/platform/build-*/dists/*/bin/*.apk
          if-no-files-found: warn
