name: build-debug

on:
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - "buildozer.spec"
      - ".github/workflows/android-debug.yml"
      - "requirements.txt"
      - "pyproject.toml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-debug:
    runs-on: ubuntu-24.04

    env:
      # Buildozer legt SDK/NDK standardmäßig unter ~/.buildozer ab
      ANDROID_HOME: ${{ github.runner.temp }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.runner.temp }}/android-sdk
      # etwas mehr Heap für Gradle in CI
      GRADLE_OPTS: -Xmx4g
      # schnelleres pip
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_PYTHON_VERSION_WARNING: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip \
            python3-venv python3-pip \
            libffi-dev libssl-dev libbz2-dev libsqlite3-dev zlib1g-dev \
            libncurses5-dev libncursesw5-dev libreadline-dev libgdbm-dev liblzma-dev \
            autoconf automake libtool pkg-config cmake

      # Caches für Buildozer/Gradle (beschleunigt Folge-Builds deutlich)
      - name: Restore caches
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            ~/.buildozer
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: Linux-buildozer-${{ hashFiles('buildozer.spec') }}-${{ hashFiles('requirements.txt', 'pyproject.toml') }}
          restore-keys: |
            Linux-buildozer-

      - name: Create venv & install Python tooling
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install cython buildozer

      - name: Set up Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools

      - name: Accept SDK licenses & install required components (API 34 / build-tools 34.0.0)
        shell: bash
        run: |
          # Sicherheitshalber die offiziellen Pfade setzen
          echo "ANDROID_HOME=${ANDROID_HOME}"
          mkdir -p "$ANDROID_SDK_ROOT"
          yes | sdkmanager --licenses

          # Gewünschte Versionen installieren
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

          # Falls Runner irgendwo 36.1 eingeschleppt hat -> hart entfernen
          rm -rf "$HOME/.buildozer/android/platform/android-sdk/build-tools/36."* || true
          rm -rf "$ANDROID_SDK_ROOT/build-tools/36."* || true

      - name: Build debug APK with Buildozer
        shell: bash
        run: |
          source .venv/bin/activate
          # Optional: etwas Debug-Ausgabe zur Kontrolle
          sdkmanager --list | sed -n '1,120p' || true

          # Buildozer-Log etwas ausführlicher
          export BUILDOZER_WARN_ON_ROOT=0
          buildozer -v android debug

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spectro-android-debug-apk
          path: |
            bin/*.apk
          if-no-files-found: error
